Add amp and speaker scoring commands :flushed:
SubZero-Robotics/2024-CommandRobot pull request #31
Opened 2024-01-23 01:22 UTC by 5690Programmers

Will merge after binding to buttons and testing

2024-01-23 23:32 UTC, having11 requested changes
LBTM
![disintegrate-1403807930](https://github.com/SubZero-Robotics/2024-CommandRobot/assets/16725165/4593eb48-3f66-4676-8ee6-b64d675773ce)

2024-01-23 23:32 UTC, having11 commented on src/main/include/commands/ScoreAmpCommand.h
> +                AddRequirements(m_intake);
Use initializer list instead of calling twice

2024-01-26 01:00 UTC, nobody5050 approved these changes

2024-01-26 01:00 UTC, nobody5050 commented on src/main/include/commands/ScoreSpeakerCommand.h
> +                if (m_score->GetMotorFreeWheel(ScoringDirection::SpeakerSide)) {
same issue as above

2024-01-26 01:02 UTC, nobody5050 reviewed
Make sure the note can’t get stuck

2024-01-26 01:39 UTC, nobody5050 approved these changes
LGTM!

2024-01-26 01:40 UTC, merged